[package]
name = "rust-quiz"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
license = "CC-BY-SA-4.0"
description = "Medium to hard Rust questions with complete explanations"
homepage = "https://dtolnay.github.io/rust-quiz"
repository = "https://github.com/dtolnay/rust-quiz"
readme = "README.md"
publish = false

[dependencies]
colored = "1.7"
futures = "0.1"
http = "0.1"
hyper = "0.12"
hyper-staticfile = "0.3"
num_cpus = "1.0"
parking_lot = "0.7"
pulldown-cmark = "0.4"
rayon = "1.0"
readonly = "0.1"
regex = "1.0"
remain = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
