[package]
name = "rust-quiz"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
pulldown-cmark = "0.2"
regex = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
